### ISSUE TITLE
Can't get the manifest file 

### ISSUE THREAD

**Issue by 1scrooge** [ibm-wsc/ibm-cloud-hpvs-sbs-byoi-lab#3]
I'm trying to deploy the secure image on the HPVS  but I have a problem. I can't get the manifest file and verify the digital signature on it.
After entering the passphrase two times nothing happens for several hours:
![image](https://user-images.githubusercontent.com/32951007/116078304-19ee7180-a69f-11eb-8776-4f6dee62b07d.png)

![image](https://user-images.githubusercontent.com/32951007/116077128-c9c2df80-a69d-11eb-9850-554cff744ac6.png)

**Comment by silliman** [comment]
Hmm..  so after you chose OK after entering the passphrase the second time, it hung up for hours?  I have never seen that before.  If you can share the region (e.g., eu-de) and location (e.g., fra02) that you are using, I can try the process there to see if the problem occurs for me.

**Comment by silliman** [comment]
Another consideration is that this lab is written with the assumption that a student would go through this lab one time in an instructor-led environment.  It is possible that if one tries this lab a second time that there could be some issues that were not anticipated in the lab instructions.

Is this the first time going through this from your x86 machine, or has it been done successfully one or more times previously?

Also, can you confirm whether or not you are building an image other than the sample "secure bitcoin wallet application" that the lab uses?  It appears from the command output that you might be building your own image.

**Comment by 1scrooge** [comment]
@silliman  I'm trying to create a secure image in the first time and I'm creating my own image, not like in the "secure bitcoin wallet app" example.
the region is eu-de and location is fra02

**Comment by silliman** [comment]
I have tried but have not been able to recreate your problem.  If this problem persists, you should open up a Case with the IBM Cloud team.  

But let me give you a few other considerations and areas to investigate.

This lab is not really designed to be run multiple times with the same directory.  In other words, I would recommend that you rename your _secure-build-cli_ directory prior to attempting to go through it again.

Two other important considerations:

The lab uses a gpg key name of _secure-build-369f0c-1_ .  You should not attempt to use this same key name if you go through the lab again, unless you delete it from your workstation first.

In other words, either change the key name,  e.g., use a different name, e.g., _secure-build-369f0c-2_ the second time, or, delete the key first by using these commands:

```
gpg --delete-secret-key secure-build-369f0c-1
gpg --delete-key secure-build-369f0c-1
```

Also, if you have already successfully created a BYOI image, if going through the lab again, you should give a unique repository name in the _sbs-config.json_ file.  That is, you should not attempt to reuse the value of the

```
"DOCKER_REPO": "secureimages/secure-bitcoin-wallet",
```

I usually add a suffix to this name that is a counter, incrementing the counter each time I go through it, e.g.,

```
"DOCKER_REPO": "secureimages/secure-bitcoin-wallet37",
```

Also, check your version of `gpg` and see if it is current or if you have the ability to update it if it is not.

I have tested this process in various environments, including the following environments, with my version of _gpg_ in each environment noted:

on my MacBook Pro, with macOS Big Sur and gpg version 2.2.27
on an Ubuntu 18.04.5 VMware guest running on my MacBook Pro, with gpg version 2.2.4
on a RHEL 8.3 x86 server, with gpg version 2.2.20

If your `gpg --version` shows a version older than these, I would see if you can upgrade your _gpg_ version.

If none of these tips help you resolve the problem, you should be able to open a case with IBM Cloud by choosing the *Support* link from the menu on the top of the IBM Cloud web user interface.

Also, even if your ultimate goal is to build an image of your own application, I would recommend trying to get through the process at least once using the sample secure bitcoin wallet application, just so we can rule out the possibility that there is something unique to your image that you built that might be causing the problem.  (I doubt this is the case but it wouldn't hurt to rule out the possibility).

**Comment by 1scrooge** [comment]
I tried to build bitcoin-wallet from scratch, just copy/paste from this tutorial and I got the same problem.
![image](https://user-images.githubusercontent.com/32951007/116226247-6e572700-a75b-11eb-9800-7e6dafb667df.png)
about OS
![image](https://user-images.githubusercontent.com/32951007/116226907-37cddc00-a75c-11eb-8442-0cbfe739e8a8.png)

**Comment by jinvanstee** [comment]
Hi @1scrooge, the development team will need to take a look at this issue. Can you open an issue here? https://github.com/ibm-hyper-protect/secure-build-cli

I'll also give the team a heads up in the Slack channel.

**Comment by KonstantinRyazantsev** [comment]
@jinvanstee we've added the issue here https://github.com/ibm-hyper-protect/secure-build-cli/issues/8

**Comment by abhiramkulkarni** [comment]
@1scrooge what we see from above logs/snapshots is that the get-manifest file is success. They would have downloaded in current working directory.

However from the stack trace seems get-config-json is stuck at generating the gpg key. Is it always giving the same stack trace ?

Can you see if "gpg --list-key" lists your key already ? And is this list output big ?

Can you get this debug.out log file by executing this command and sent to my slack id @abhiram
 ./build.py get-config-json --env sbs-config.json --key-id <yourkey> --loglevel DEBUG -v >>   debug.out

@silliman

**Comment by 1scrooge** [comment]
Hi @abhiramkulkarni .
Sorry for the late response. We have tried different configurations, and with Ubuntu 20.04 we were able to build it. I don't know what was wrong with Ubuntu 18.04

**Comment by 1scrooge** [comment]
@abhiramkulkarni it is the log from ubuntu 18.04 
```

**Comment by 1scrooge** [comment]
@abhiramkulkarni I got the debug log, but I can't send it to slack. Can you share your telegram?
